name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set git user config
        uses: fregante/setup-git-user@v1

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install and Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll

      - name: Push to gh-pages
        run: |
          git add -f out/
          git checkout -b temp-for-deploy-gh-pages
          git commit -m "Deploy Next.js to gh-pages"
          git subtree split --prefix out -b gh-pages
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages
          git checkout main
          git branch -D temp-for-deploy-gh-pages         
